### ISSUE TITLE
Weekly Scrap By Workcenter

### ISSUE THREAD

**Issue by NDMO** [bezlio/bezlio-recipes#10]
Create a line chart with each workcenter being a region and the axis being week numbers versus units scrapped.  This project should first be written targeting Excel with ODBC and committed to 'master'.  The it shoud be ported to Epicor10, Epicor905, and Visual70.

**Comment by aellis** [comment]
Matt H was assigned to this one. Work with him to get this committed to the recipe book. The completion of this task should include the creation of a README.md committed to the recipe book and information on this Bezl on the initial README.md which serves as an index. This Bezl should be added with relevant queries to each branch and verified by Matt to work with each.

**Comment by aellis** [comment]
Closing this out in support of the new focus purely on sales roles initially.  This will be re-opened when focus will be moved to this role.
