### ISSUE TITLE
Budgets By Department

### ISSUE THREAD

**Issue by NDMO** [bezlio/bezlio-recipes#11]
Develop a solution that allows for expense budgets to be established by department by year that are cross-referenced to actual expenses attributed to them.  The Bezl should allow for maintenance of the department budgets.  It should also automatically determine if a user is a member of a department, in which case they can only see their own data, or a manager where they will see all data.  A bar chart of budget versus actual should be shown.  A version should be developed for Excal target to the master branch first, then Visual, and then see if parallel concepts exist in Epicor so to make this sensible to port there.

**Comment by aellis** [comment]
Closed out while refocused approach on sales roles being defined.
