### ISSUE TITLE
Customer Map View With CRM Call Logging

### ISSUE THREAD

**Issue by NDMO** [bezlio/bezlio-recipes#12]
This one will use Google Maps to show a sales person all of their customers on a map view.  Pins can be clicked to bring up customer details to the right-hand side with a click-to-dial phone number, GPS-routeable address, contact info, and a text box with a submit to log a CRM call to this customer.  A version should be developed for Excal target to the master branch first, then Visual, and then see if parallel concepts exist in Epicor so to make this sensible to port there.

**Comment by aellis** [comment]
The details of this issue were revised slightly, but @OnlyAGhost has been working on this so assigning to him.

**Comment by aellis** [comment]
This issue has been deprecated.
