### ISSUE TITLE
Interactive Picklist

### ISSUE THREAD

**Issue by NDMO** [bezlio/bezlio-recipes#14]
This Bezl will be an interactive tool that combines the printed sales order picklist with the process of creating shipment records.  The following are points on how it will operate:

1. It should start off as a HTML table of parts to pick much like all sales order picklists operate.  It should be sorted by a custom warehouse / bin picking sequence we will pull from an Excel spreadsheet.  
2. The main row info will be details about the bin you are picking from and then below that will be each part to pull.  Each part will have a "pick" button next to it.
3. Upon clicking the pick button the UI will switch to where you can see the individual orders it is being picked for and the quantities being picked for each.  A 'fill all' button should be present to auto-populate each order with the full required quantity.
4. A save button will be present on the part drill-down which will create or update the shipment adding in this new part and refreshing the main view so to drop-them off the pick list.

This project should first be written targeting Excel with ODBC and committed to 'master'.  The it shoud be ported to Epicor10, Epicor905, and Visual70.

**Comment by aellis** [comment]
Closed out while refocused approach on sales roles being defined.
