### ISSUE TITLE
Manufacturing Window Notation Maintenance

### ISSUE THREAD

**Issue by NDMO** [bezlio/bezlio-recipes#15]
This is a port of the existing Manufacturing Window Notation Maintenance for Visual.  I don't recall a lot of the details but am pretty sure this was just a standard SQL query thing that should be pretty easy to port.  A version should be developed for Excal target to the master branch first, then Visual, and then see if parallel concepts exist in Epicor so to make this sensible to port there.

**Comment by aellis** [comment]
Closing this out in support of the new focus purely on sales roles initially.  This will be re-opened when focus will be moved to this role.
