### ISSUE TITLE
Mass Material Movement Screen

### ISSUE THREAD

**Issue by NDMO** [bezlio/bezlio-recipes#16]
This Bezl will be a port of our existing Epicor mass material movement screen, although the UI may be tweaked given the superior controls available in a web project.  In short, it pulls in a list of all inventory in a given location and allows you to transfer it to another location.  This project should first be written targeting Excel with ODBC and committed to 'master'.  The it shoud be ported to Epicor10, Epicor905, and Visual70.

**Comment by aellis** [comment]
Closed out while refocused approach on sales roles being defined.
