### ISSUE TITLE
Orders booked by month

### ISSUE THREAD

**Issue by NDMO** [bezlio/bezlio-recipes#18]
The attached Bezl should be wired up to work for VISUAL.  Add this to the recipe book along with this .SQL:

SELECT
  DATEADD(dd, @@DATEFIRST - DATEPART(dw, ORDER_DATE) - 6, ORDER_DATE) AS WEEK_OF
  , SUM(CUST_ORDER_LINE.TOTAL_AMT_ORDERED) AS WEEK_BOOKINGS
  , SUM(CASE WHEN SHIP_PERIOD.BEGIN_DATE = ORDER_PERIOD.BEGIN_DATE THEN CUST_ORDER_LINE.TOTAL_AMT_ORDERED ELSE 0 END) AS
 IN_PERIOD_BOOKINGS
FROM
  CUSTOMER_ORDER 

  INNER JOIN CUST_ORDER_LINE ON 
  CUSTOMER_ORDER.ID = CUST_ORDER_LINE.CUST_ORDER_ID

  INNER JOIN ACCOUNT_PERIOD SHIP_PERIOD ON
  SHIP_PERIOD.BEGIN_DATE <= CUSTOMER_ORDER.DESIRED_SHIP_DATE
  AND SHIP_PERIOD.END_DATE >= CUSTOMER_ORDER.DESIRED_SHIP_DATE

  INNER JOIN ACCOUNT_PERIOD ORDER_PERIOD ON
  ORDER_PERIOD.BEGIN_DATE <= CUSTOMER_ORDER.ORDER_DATE
  AND ORDER_PERIOD.END_DATE >= CUSTOMER_ORDER.ORDER_DATE
WHERE
  DATEDIFF (ww , ORDER_DATE , GETDATE()) <= 52
GROUP BY
  DATEADD(dd, @@DATEFIRST - DATEPART(dw, ORDER_DATE) - 6, ORDER_DATE)
ORDER BY
  WEEK_OF DESC

Then port this to Excel, Epicor10, and Epicor905.

**Comment by aellis** [comment]
Closed out while refocused approach on sales roles being defined.
