### ISSUE TITLE
Real-time Time Tracking

### ISSUE THREAD

**Issue by NDMO** [bezlio/bezlio-recipes#21]
This will simply be a variation to https://github.com/bezlio/bezlio-recipes/tree/master/time-tracking/multi-job-hours-only.  In this variation, as opposed to allowing users to manually specify time they instead "clock on" to the selected jobs and it tracks their time as the clock runs.  A version should be developed for Excal target to the master branch first, then Visual, and then see if parallel concepts exist in Epicor so to make this sensible to port there.

**Comment by aellis** [comment]
Closed out while refocused approach on sales roles being defined.
