### ISSUE TITLE
Salesperson Sales Versus Quota

### ISSUE THREAD

**Issue by NDMO** [bezlio/bezlio-recipes#22]
A horizontal bar chart should be developed showing salesperson sales versus a quota stored in Excel.  Bezl should automatically detect if the salesperson is logged in and only show their data as opposed to a manager that can see all sales people.  Each bar can be clicked on for a drill-down to see a break-down by customer.  A version should be developed for Excal target to the master branch first, then Visual, and then see if parallel concepts exist in Epicor so to make this sensible to port there.

**Comment by aellis** [comment]
Closed out while refocused approach on sales roles being defined.
