### ISSUE TITLE
Company Directory

### ISSUE THREAD

**Issue by NDMO** [bezlio/bezlio-recipes#23]
A very simply company directory with names, phone numbers broken down by department.  Search tools at the top.  This should target all branches.

**Comment by aellis** [comment]
Tony was assigned to this one.  Work with him to get this committed to the recipe book.  The completion of this task should include the creation of a README.md committed to the recipe book and information on this Bezl on the initial README.md which serves as an index.

**Comment by aellis** [comment]
Closing this out in support of the new focus purely on sales roles initially.  This will be re-opened when focus will be moved to this role.
