### ISSUE TITLE
Company Calendar

### ISSUE THREAD

**Issue by NDMO** [bezlio/bezlio-recipes#4]
Use the calendar view to show a company calendar that pulls data from an Excel spreadsheet. Clicking on an event should show details. Also make an event category that can be applied to events that can be toggled on / off. This will be an Excel-only recipe.

**Comment by aellis** [comment]
Nick completed an initial version of this.  Adam to review.

**Comment by aellis** [comment]
Closing this out in support of the new focus purely on sales roles initially.  This will be re-opened when focus will be moved to this role.
