### ISSUE TITLE
Top 25 Customers

### ISSUE THREAD

**Issue by NDMO** [bezlio/bezlio-recipes#9]
Create a horizontal bar chart showing the top 25 customers according to sales sorted with the highest sales first.  The chart type 'horizontal-bar' in Chart.js will handle the layout.  This project should first be written targeting Excel with ODBC and committed to 'master'.  The it shoud be ported to Epicor10, Epicor905, and Visual70.

**Comment by aellis** [comment]
Matt H was assigned to this one. Work with him to get this committed to the recipe book. The completion of this task should include the creation of a README.md committed to the recipe book and information on this Bezl on the initial README.md which serves as an index. This Bezl should be added with relevant queries to each branch and verified by Matt to work with each.

**Comment by aellis** [comment]
Closing this out in support of the new focus purely on sales roles initially.  This will be re-opened when focus will be moved to this role.
